{
 "title": "myapp Application Information",
 "description": "Information about myapp",
 "tags": [ "myapp" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "loglevel",
    "query": "critical, error, warning, info, debug, trace"
   }
  ]
 },
 "panels": [
  {
   "title": "Application Name",
   "type": "stat",
   "description": "Project name from package.json",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_server_info" }
   ]
  },
  {
   "title": "Application Version",
   "type": "stat",
   "description": "Application version from package.json",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_server_info" }
   ]
  },
  {
   "title": "Logs Timeline ",
   "type": "timeseries",
   "description": "Shows a timeline of logs with color coded level",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count_over_time({app=\"myapp\"}[$__interval] |~ `\"level\":\"${loglevel:regex}\"`|~ `\"level\":\"info\"`)",
     "legendFormat": "Info"
    },
    {
     "expr": "count_over_time({app=\"myapp\"}[$__interval] |~ `\"level\":\"${loglevel:regex}\"` |~ `\"level\":\"debug\"`)",
     "legendFormat": "Debug"
    },
    {
     "expr": "count_over_time({app=\"myapp\"}[$__interval] |~ `\"level\":\"${loglevel:regex}\"`|~ `\"level\":\"error\"`)",
     "legendFormat": "Error"
    },
    {
     "expr": "count_over_time({app=\"myapp\"}[$__interval] |~ `\"level\":\"${loglevel:regex}\"` |~ `\"level\":\"trace\"`)",
     "legendFormat": "Trace"
    },
    {
     "expr": "count_over_time({app=\"myapp\"}[$__interval] |~ `\"level\":\"${loglevel:regex}\"` |~ `\"level\":\"critical\"`)",
     "legendFormat": "Critical"
    },
    {
     "expr": "count_over_time({app=\"myapp\"}[$__interval] |~ `\"level\":\"${loglevel:regex}\"` |~ `\"level\":\"warning\"`)",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Logs (${loglevel:regex})",
   "type": "logs",
   "description": "Showing Logs over Time",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"myapp\"} |~ `\"level\":\"${loglevel:regex}\"`",
     "measurement": "host_cpu",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}