{
 "title": "InfluxDB stats",
 "description": "Influxdb stats from Prometheus",
 "tags": [
  "logging",
  "influxdb"
 ],
 "time": { "from": "now-60m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(influxdb_exporter_stats_query_success, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success"
    }
   ]
  },
  {
   "title": "AVG query duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "influxdb_query_executor_query_duration_ns{instance=~\"$instance.*\"} / influxdb_query_executor_queries_finished",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queries executed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(influxdb_query_executor_queries_executed[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Measurements",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "influxdb_database_num_measurements{instance=~\"$instance.*\", database!=\"_internal\"}",
     "legendFormat": "{{instance}} / {{ database }}"
    }
   ]
  },
  {
   "title": "Series",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "influxdb_database_num_series{instance=~\"$instance.*\", database!=\"_internal\"}",
     "legendFormat": "{{instance}} / {{ database }}"
    }
   ]
  },
  {
   "title": "Continuous Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(influxdb_cq_query_ok{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "OK {{ instance }}"
    },
    {
     "expr": "increase(influxdb_cq_query_fail{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "FAIL {{ instance }}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "influxdb_runtime_heap_alloc{instance=~\"$instance.*\"}",
     "legendFormat": "Allocated {{ instance }}"
    },
    {
     "expr": "influxdb_runtime_heap_idle{instance=~\"$instance.*\"}",
     "legendFormat": "Idle {{ instance }}"
    },
    {
     "expr": "influxdb_runtime_heap_in_use{instance=~\"$instance.*\"}",
     "legendFormat": "In use {{ instance }}"
    },
    {
     "expr": "influxdb_runtime_heap_released{instance=~\"$instance.*\"}",
     "legendFormat": "Released {{ instance }}"
    },
    {
     "expr": "influxdb_runtime_heap_sys{instance=~\"$instance.*\"}",
     "legendFormat": "Sys {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "influxdb_runtime_alloc{instance=~\"$instance.*\"}",
     "legendFormat": "Allocated {{ instance }}"
    },
    {
     "expr": "influxdb_runtime_frees{instance=~\"$instance.*\"}",
     "legendFormat": "Frees {{ instance }}"
    },
    {
     "expr": "influxdb_runtime_sys{instance=~\"$instance.*\"}",
     "legendFormat": "Sys {{ instance }}"
    }
   ]
  },
  {
   "title": "GCs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(influxdb_runtime_num_g_c{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "Allocated {{ instance }}"
    }
   ]
  },
  { "title": "Shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Disk Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(influxdb_shard_disk_bytes{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "{{ instance }} / {{ database }}"
    }
   ]
  },
  {
   "title": "Write ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(influxdb_shard_write_points_ok{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "{{ instance }} / {{ database }}"
    }
   ]
  },
  {
   "title": "Written Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(influxdb_shard_write_bytes{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "{{ instance }} / {{ database }}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Cache age",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "influxdb_tsm1_cache_cache_age_ms{instance=~\"$instance.*\", database!=\"_internal\"}"
    }
   ]
  },
  {
   "title": "Cached bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_cache_cached_bytes{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "{{ instance }} / {{ database }}"
    }
   ]
  },
  {
   "title": "Cached DISK bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_cache_disk_bytes{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "{{ instance }} / {{ database }}"
    }
   ]
  },
  {
   "title": "Cached MEM bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_cache_mem_bytes{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "{{ instance }} / {{ database }}"
    }
   ]
  },
  { "title": "Compactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Compaction duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_engine_cache_compaction_duration{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "Cache {{ instance }} / {{ database }}"
    },
    {
     "expr": "sum(influxdb_tsm1_engine_tsm_full_compaction_duration{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "Full {{ instance }} / {{ database }}"
    },
    {
     "expr": "sum(influxdb_tsm1_engine_tsm_level1_compaction_duration{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "Level 1 {{ instance }} / {{ database }}"
    },
    {
     "expr": "sum(influxdb_tsm1_engine_tsm_level2_compaction_duration{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "Level 2 {{ instance }} / {{ database }}"
    },
    {
     "expr": "sum(influxdb_tsm1_engine_tsm_level3_compaction_duration{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "Level 3 {{ instance }} / {{ database }}"
    },
    {
     "expr": "sum(influxdb_tsm1_engine_tsm_optimize_compaction_duration{instance=~\"$instance.*\", database!=\"_internal\"}) by (instance, database)",
     "legendFormat": "Optimize {{ instance }} / {{ database }}"
    }
   ]
  }
 ]
}